# Where to plot and log.
directories:
  # One directory in which to store all plot job logs (the STDOUT/
  # STDERR of all plot jobs).  In order to monitor progress, plotman
  # reads these logs on a regular basis, so using a fast drive is
  # recommended.
  log: /home/cs/disk_md0/logs/chia

  # One or more directories to use as tmp dirs for plotting.  The
  # scheduler will use all of them and distribute jobs among them.
  # It assumes that IO is independent for each one (i.e., that each
  # one is on a different physical device).
  #
  # If multiple directories share a common prefix, reports will
  # abbreviate and show just the uniquely identifying suffix.
  tmp:
    - /home/cs/disk_md0/chia_tmp/0
    - /home/cs/disk_md0/chia_tmp/1
    - /home/cs/disk_md0/chia_tmp/2
    - /home/cs/disk_md0/chia_tmp/3
    - /home/cs/disk_md0/chia_tmp/4
    - /home/cs/disk_md0/chia_tmp/5
    - /home/cs/disk_md0/chia_tmp/6
    - /home/cs/disk_md0/chia_tmp/7
    - /home/cs/disk_md0/chia_tmp/8
    - /home/cs/disk_md0/chia_tmp/9
    # - /mnt/tmp/01
    # - /mnt/tmp/02
    # - /mnt/tmp/03

  # Optional: tmp2 directory.  If specified, will be passed to
  # chia plots create as -2.  Only one tmp2 directory is supported.
  # tmp2: /mnt/tmp/a

  # One or more directories; the scheduler will use all of them.
  # These again are presumed to be on independent physical devices,
  # so writes (plot jobs) and reads (archivals) can be scheduled
  # to minimize IO contention.
  dst:
    - /home/cs/data0/chia
    # - /mnt/dst/01

  # Archival configuration.  Optional; if you do not wish to run the
  # archiving operation, comment this section out.
  #
  # Currently archival depends on an rsync daemon running on the remote
  # host, and that the module is configured to match the local path.
  # See code for details.
  archive:
    rsyncd_module: plots
    rsyncd_path: /plots
    rsyncd_bwlimit: 80000  # Bandwidth limit in KB/s
    rsyncd_host: myfarmer
    rsyncd_user: chia


# Plotting scheduling parameters
scheduling:
  # Don't run a job on a particular temp dir until all existing jobs
  # have progresed at least this far.  Phase major corresponds to the
  # plot phase, phase minor corresponds to the table or table pair
  # in sequence.
  tmpdir_stagger_phase_major: 2
  tmpdir_stagger_phase_minor: 1

  # Don't run more than this many jobs at a time on a single temp dir.
  tmpdir_max_jobs: 8

  # Don't run any jobs (across all temp dirs) more often than this.
  global_stagger_m: 30

  # How often the daemon wakes to consider starting a new plot job
  polling_time_s: 10

# Plotting parameters.  These are pass-through parameters to chia plots create.
# See documentation at
# https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#create
plotting:
  k: 32
  e: True              # Use -e plotting option
  n_threads: 16         # Threads per job
  n_buckets: 128       # Number of buckets to split data into
  job_buffer: 5000     # Per job memory
